### ISSUE TITLE
Can It be this be upgraded to current factorio version 1.1

### ISSUE THREAD

**Issue by nkv123** [Triavanicus/TriCircuits#3]
It would be nice if it could be upgraded to current factorio version

**Comment by Triavanicus** [comment]
I have no idea, as I haven't played Factorio in a few years. However if anyone would like to modify/update it, they can feel free to do so. I will have to add a permissive license before so, so hang tight.

**Comment by Triavanicus** [comment]
I added the MIT license, so feel free to do whatever with it :)
